#!/bin/bash

set -euo pipefail

BBL_STATE_DIRECTORY=$1
iaas=$2
concourse_dir="${iaas}-bbl"
export BBL_STATE_DIRECTORY

eval "$(bbl print-env)"
concourse_secrets_lpass_note_id=$(bosh int "$concourse_dir/director.yml" --path='/concourse_secrets_lpass_note_id')
creds_note_id=$(bosh int "${concourse_dir}/director.yml" --path='/private_note_id')
creds_attachment_id=$(bosh int "${concourse_dir}/director.yml" --path='/private_attachment_id')
private_yml=$(echo y | lpass show "$creds_note_id" --attach="$creds_attachment_id")

bosh deploy -d concourse \
  "${concourse_dir}/workers.yml" \
  --vars-file <(echo "$private_yml") \
  --vars-file <(bosh int <(lpass show --note "$concourse_secrets_lpass_note_id")) \
