#!/bin/bash
set -e -o pipefail

bin_dir=$(dirname "${BASH_SOURCE[0]}")
CONCOURSE_DIR="$(cd "$bin_dir/.."; pwd)"

print_usage(){
  echo "Usage: $0 <bosh_deployment> <iaas>"
}

BOSH_DEPLOYMENT="$1"
IAAS="$2"

if [ -z "$BOSH_DEPLOYMENT" ]; then
  print_usage
  exit 1
fi

if [ -z "$IAAS" ]; then
  print_usage
  exit 1
fi

set -u

BOSH_DEPLOYMENT=$(cd "$BOSH_DEPLOYMENT"; pwd)

secrets_lpass_note_id=$(bosh-cli int "$CONCOURSE_DIR/$IAAS/director.yml" --path='/secrets_lpass_note_id')

manifest_file=$(mktemp)

secret=$(lpass show --note "$secrets_lpass_note_id")

if bosh-cli int "$CONCOURSE_DIR/$IAAS/director.yml" --path='/secrets_lpass_note_path'; then
  secrets_lpass_note_path=$(bosh-cli int "$CONCOURSE_DIR/$IAAS/director.yml" --path='/secrets_lpass_note_path')
  secret=$(echo -n "$secret" | bosh int - --path="/$secrets_lpass_note_path")
fi
echo "$secret"

if [ "$IAAS" == "vsphere" ]; then
  bosh-cli interpolate "$BOSH_DEPLOYMENT/bosh.yml"  \
    --ops-file "$BOSH_DEPLOYMENT/$IAAS/cpi.yml" \
    --ops-file "$BOSH_DEPLOYMENT/vsphere/resource-pool.yml" \
    --vars-file "$CONCOURSE_DIR/$IAAS/director.yml" \
    --vars-file <(echo -n "$secret") \
    > "$manifest_file"
else
  bosh-cli interpolate "$BOSH_DEPLOYMENT/bosh.yml"  \
      --ops-file "$BOSH_DEPLOYMENT/$IAAS/cpi.yml" \
      --vars-file "$CONCOURSE_DIR/$IAAS/director.yml" \
    --vars-file <(echo -n "$secret") \
    > "$manifest_file"
fi

bosh-cli create-env "$manifest_file" \
    --vars-store "$CONCOURSE_DIR/$IAAS/private.yml" \
    --state "$CONCOURSE_DIR/$IAAS/state.json"

