#!/bin/bash
set -ex -o pipefail

bin_dir=$(dirname "${BASH_SOURCE[0]}")
CONCOURSE_DIR="$(cd "$bin_dir/.."; pwd)"

print_usage(){
  echo "Usage: $0 <bosh_deployment> <iaas>"
}

BOSH_DEPLOYMENT="$1"
IAAS="$2"

if [ -z "$BOSH_DEPLOYMENT" ]; then
  print_usage
  exit 1
fi

if [ -z "$IAAS" ]; then
  print_usage
  exit 1
fi

set -u

BOSH_DEPLOYMENT=$(cd "$BOSH_DEPLOYMENT"; pwd)
director_yml="$CONCOURSE_DIR/$IAAS/director.yml"

secrets_lpass_note_id=$(bosh-cli int "${director_yml}" --path='/private_note_id')

manifest_file=$(mktemp)

secret=$(lpass show --note "$secrets_lpass_note_id")

if [ "$IAAS" == "vsphere" ]; then
  bosh-cli interpolate "$BOSH_DEPLOYMENT/bosh.yml"  \
    --ops-file "$BOSH_DEPLOYMENT/$IAAS/cpi.yml" \
    --ops-file "$BOSH_DEPLOYMENT/vsphere/resource-pool.yml" \
    --vars-file "${director_yml}" \
    --vars-file <(echo -n "$secret") \
    > "$manifest_file"
elif [ "$IAAS" == "openstack" ]; then
  openstack_credentials_note_id="$(bosh-cli int "${director_yml}" --path='/openstack_account_id')"
  openstack_secrets_path="$(bosh-cli int "${director_yml}" --path='/secrets_lpass_note_path')"
  openstack_credentials="$(bosh-cli int <(echo "$(lpass show --note ${openstack_credentials_note_id})") --path=/${openstack_secrets_path})"

  bosh-cli interpolate "$BOSH_DEPLOYMENT/bosh.yml"  \
    --ops-file "$BOSH_DEPLOYMENT/$IAAS/cpi.yml" \
    --ops-file "$CONCOURSE_DIR/$IAAS/nova.yml" \
    --vars-file "${director_yml}" \
    --vars-file <(echo -n "$secret") \
    --vars-file <(echo -n "$openstack_credentials") \
    > "$manifest_file"
elif [[ "${IAAS}" == "gcp" ]]; then

  gcp_credentials_note_id="$(bosh-cli int "${director_yml}" --path='/service_account_lpass_note_id')"
  gcp_credentials="$(lpass show --note ${gcp_credentials_note_id})"

  bosh-cli interpolate "$BOSH_DEPLOYMENT/bosh.yml"  \
    --ops-file "$BOSH_DEPLOYMENT/$IAAS/cpi.yml" \
    --ops-file "$BOSH_DEPLOYMENT/uaa.yml" \
    --ops-file "$BOSH_DEPLOYMENT/credhub.yml" \
    --vars-file "${director_yml}" \
    --var-file gcp_credentials_json=<(echo -n ${gcp_credentials}) \
    --vars-file <(echo -n "$secret") \
    > "$manifest_file"
else
  bosh-cli interpolate "$BOSH_DEPLOYMENT/bosh.yml"  \
    --ops-file "$BOSH_DEPLOYMENT/$IAAS/cpi.yml" \
    --vars-file "${director_yml}" \
    --vars-file <(echo -n "$secret") \
    > "$manifest_file"
fi

bosh-cli create-env "$manifest_file" \
    --vars-store "$CONCOURSE_DIR/$IAAS/private.yml" \
    --state "$CONCOURSE_DIR/$IAAS/state.json"

