#!/bin/bash
set -e -o pipefail

bin_dir=$(dirname "${BASH_SOURCE[0]}")
CONCOURSE_DIR="$HOME/workspace/kubo-ci/concourse"

print_usage(){
  echo "Usage: $0 <bosh_deployment> <iaas>"
}

BOSH_DEPLOYMENT="$1"
IAAS="vsphere"

if [ -z "$BOSH_DEPLOYMENT" ]; then
  print_usage
  exit 1
fi
director_yml="$CONCOURSE_DIR/$IAAS/director.yml"


  bosh create-env "$BOSH_DEPLOYMENT/bosh.yml"  \
    --ops-file "$BOSH_DEPLOYMENT/$IAAS/cpi.yml" \
    --ops-file "$BOSH_DEPLOYMENT/vsphere/resource-pool.yml" \
    --ops-file "$BOSH_DEPLOYMENT/uaa.yml" \
    --ops-file "$BOSH_DEPLOYMENT/credhub.yml" \
    --vars-file "${director_yml}" \
    --vars-file "$CONCOURSE_DIR/$IAAS/creds.yml" \
    --ops-file "$BOSH_DEPLOYMENT/jumpbox-user.yml" \
    --vars-store "$CONCOURSE_DIR/$IAAS/private.yml" \
    --state "$CONCOURSE_DIR/$IAAS/state.json"

