#!/bin/bash

set -euo pipefail

BBL_STATE_DIRECTORY=$1
manifest=$2
export BBL_STATE_DIRECTORY

eval "$(bbl print-env)"

lpass_note_id="$(cat "$BBL_STATE_DIRECTORY/vars/concourse_secrets")"

bosh deploy -d concourse "$manifest" --vars-file <(lpass show "$lpass_note_id" --notes)
