---
resource_types:
- name: github-release-with-version-filtering
  type: docker-image
  source:
    repository: pcfkubo/github-release-resource
    tag: filter-version

resources:
- name: etcd-release
  type: github-release-with-version-filtering
  source:
    owner: etcd-io
    repository: etcd
    version_filter: "< 3.4.0"
    access_token: ((github-token-key))

- name: git-cfcr-etcd
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/cfcr-etcd-release.git
    branch: master
    private_key: ((git-ssh-key.private_key))

- name: git-kubo-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/kubo-ci
    branch: master

jobs:
- name: bump-etcd
  plan:
  - in_parallel:
    - get: git-kubo-ci
    - get: git-cfcr-etcd
    - get: etcd-release
      trigger: true
      params: { globs: ["etcd-*-linux-amd64.tar.gz"] }
  - task: bump-etcd-release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/kubo-ci
          tag: stable
      run:
        path: git-kubo-ci/scripts/bump-etcd.sh
      inputs:
        - name: git-kubo-ci
        - name: git-cfcr-etcd
        - name: etcd-release
      outputs:
        - name: git-cfcr-etcd-output
      params:
        GCS_JSON_KEY: ((gcs-json-key))
  - put: git-cfcr-etcd
    params:
      repository: git-cfcr-etcd-output
