---
resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: git-kubo-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-ci.git
    branch: master
    private_key: ((git-ssh-key.private_key))

- name: git-kubo-release
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-release.git
    branch: master
    private_key: ((git-ssh-key.private_key))
    ignore_paths:
    - '*.md'
    - 'LICENSE'
    - 'NOTICE'

- name: git-kubo-etcd
  type: git
  source:
    uri: git@github.com:pivotal-cf-experimental/kubo-etcd.git
    branch: master
    private_key: ((git-ssh-key.private_key))
    ignore_paths:
    - '*.md'
    - 'LICENSE'
    - 'NOTICE'

- name: git-docker-boshrelease
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/docker-boshrelease.git
    branch: master
    private_key: ((git-ssh-key.private_key))
    ignore_paths:
    - '*.md'
    - 'LICENSE'
    - 'NOTICE'

- name: git-cfcr-etcd-release
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/cfcr-etcd-release.git
    branch: master
    private_key: ((git-ssh-key.private_key))
    ignore_paths:
    - '*.md'
    - 'LICENSE'
    - 'NOTICE'


- name: golang-release
  type: git
  source:
    uri: https://github.com/bosh-packages/golang-release
    branch: master

- name: git-golang-release
  type: github-release
  source:
    owner: bosh-packages
    repository: golang-release
    access_token: ((github-token-key))

- name: golang-version
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    versioned_file: component-golang-version

############################################
# Jobs
############################################
jobs:
- name: update-component-golang-version
  #disable_manual_trigger: true
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-golang-release
      trigger: true
      params:
        include_source_tarball: true
    - get: golang-version
  - task: get-latest-version
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/kubo-ci
          tag: stable
      run:
        path: git-kubo-ci/scripts/bump-golang-component-version.sh
      inputs:
        - name: git-kubo-ci
        - name: git-golang-release
        - name: golang-version
      outputs:
        - name: modified-golang-version
  - put: golang-version
    params:
      file: modified-golang-version/component-golang-version

- name: bump-docker-boshrelease-golang
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-docker-boshrelease
    - get: golang-release
    - get: golang-version
      trigger: true
  - task: bump-release-golang
    file: git-kubo-ci/tasks/bump-release-golang.yml
    input_mapping: { release: git-docker-boshrelease }
    params:
      ACCESS_KEY_ID: ((gcs-access-key-id))
      SECRET_ACCESS_KEY: ((gcs-secret-access-key))
  - task: check-create-release
    file: git-kubo-ci/tasks/bump/check-create-release.yml
  - put: git-docker-boshrelease
    params:
      repository: modified-release
      rebase: true

- name: bump-kubo-release-golang
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-release
    - get: golang-release
    - get: golang-version
      trigger: true
  - task: bump-release-golang
    file: git-kubo-ci/tasks/bump-release-golang.yml
    input_mapping: { release: git-kubo-release }
    params:
      ACCESS_KEY_ID: ((gcs-access-key-id))
      SECRET_ACCESS_KEY: ((gcs-secret-access-key))
  - task: check-create-release
    file: git-kubo-ci/tasks/bump/check-create-release.yml
  - put: git-kubo-release
    params:
      repository: modified-release
      rebase: true

- name: bump-kubo-etcd-golang
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-etcd
    - get: golang-release
    - get: golang-version
      trigger: true
  - task: bump-release-golang
    file: git-kubo-ci/tasks/bump-release-golang.yml
    input_mapping: { release: git-kubo-etcd }
    params:
      ACCESS_KEY_ID: ((gcs-access-key-id))
      SECRET_ACCESS_KEY: ((gcs-secret-access-key))
  - task: check-create-release
    file: git-kubo-ci/tasks/bump/check-create-release.yml
  - put: git-kubo-etcd
    params:
      repository: modified-release
      rebase: true

- name: bump-cfcr-etcd-release-golang
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-cfcr-etcd-release
    - get: golang-release
    - get: golang-version
      trigger: true
  - task: bump-release-golang
    file: git-kubo-ci/tasks/bump-release-golang.yml
    input_mapping: { release: git-cfcr-etcd-release }
    params:
      ACCESS_KEY_ID: ((gcs-access-key-id))
      SECRET_ACCESS_KEY: ((gcs-secret-access-key))
  - task: check-create-release
    file: git-kubo-ci/tasks/bump/check-create-release.yml
  - put: git-cfcr-etcd-release
    params:
      repository: modified-release
      rebase: true

- name: bump-docker-image-golang
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: golang-version
      trigger: true
  - task: bump-golang
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/kubo-ci
          tag: stable
      run:
        path: git-kubo-ci/scripts/bump-docker-image-golang.sh
      inputs:
        - name: git-kubo-ci
        - name: golang-version
      outputs:
        - name: git-kubo-ci-output
  - put: git-kubo-ci
    params:
      repository: git-kubo-ci-output
      rebase: true
