---
resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

resources:
- name: git-kubo-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/kubo-ci
    branch: master

- name: git-kubo-deployment
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-deployment.git
    branch: develop
    private_key: ((git-ssh-key.private_key))

- name: cfcr-etcd-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/cfcr-etcd-release

- name: bpm-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/bpm-release

- name: docker-boshrelease
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/docker-boshrelease

- name: windows-tools-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/windows-tools-release

- name: windows-utilities-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/windows-utilities-release


- name: gcs-precompiled-cfcr-etcd-untested
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-precompiled-releases
    regexp: cfcr-etcd-(.*).tgz

- name: gcs-precompiled-docker-untested
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-precompiled-releases
    regexp: docker-(.*).tgz

- name: gcs-precompiled-bpm-untested
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-precompiled-releases
    regexp: bpm-(.*).tgz

- name: compilation-deployment
  type: bosh-deployment
  source:
    deployment: compilation
    skip_check: true

- name: gcs-source-json
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    versioned_file: gaffer-env/source.json

jobs:
- name: bump-bpm-release
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-deployment
    - get: gcs-source-json
    - get: bpm-release
      trigger: true
  - task: bump-boshrelease
    file: git-kubo-ci/tasks/bump-boshrelease.yml
    input_mapping:
      boshrelease: bpm-release
    params:
      RELEASE_NAME: bpm
  - task: generate-compilation-manifest
    file: git-kubo-ci/tasks/generate-compilation-manifest.yml
    input_mapping:
      git-kubo-deployment: git-kubo-deployment-output
    params:
      RELEASE_LIST: "bpm"
  - put: compilation-deployment
    params:
      manifest: compilation-manifest/manifest.yml
      source_file: gcs-source-json/source.json
    tags: ['gaffer']
  - task: export
    tags: ['gaffer']
    file: git-kubo-ci/tasks/export-release.yml
    input_mapping:
      git-kubo-deployment: git-kubo-deployment-output
    params:
      RELEASE_LIST: "bpm"
  - put: gcs-precompiled-bpm-untested
    params:
      file: compiled-releases/bpm-*.tgz
  - task: bump-precompiled-releases-in-manifest
    file: git-kubo-ci/tasks/bump-precompiled-releases-in-manifest.yml
    input_mapping:
      git-kubo-deployment: git-kubo-deployment-output
    params:
      RELEASE_LIST: "bpm"
  - put: git-kubo-deployment
    params:
      repository: git-kubo-deployment-output

- name: bump-etcd-release
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-deployment
    - get: gcs-source-json
    - get: cfcr-etcd-release
      trigger: true
  - task: bump-etcd-release
    file: git-kubo-ci/tasks/bump-boshrelease.yml
    input_mapping:
       boshrelease: cfcr-etcd-release
    params:
      RELEASE_NAME: cfcr-etcd
  - task: generate-compilation-manifest
    file: git-kubo-ci/tasks/generate-compilation-manifest.yml
    input_mapping:
      git-kubo-deployment: git-kubo-deployment-output
    params:
      RELEASE_LIST: "cfcr-etcd"
  - put: compilation-deployment
    params:
      manifest: compilation-manifest/manifest.yml
      source_file: gcs-source-json/source.json
    tags: ['gaffer']
  - task: export
    tags: ['gaffer']
    file: git-kubo-ci/tasks/export-release.yml
    input_mapping:
      git-kubo-deployment: git-kubo-deployment-output
    params:
      RELEASE_LIST: "cfcr-etcd"
  - put: gcs-precompiled-cfcr-etcd-untested
    params:
      file: compiled-releases/cfcr-etcd-*.tgz
  - task: bump-precompiled-releases-in-manifest
    file: git-kubo-ci/tasks/bump-precompiled-releases-in-manifest.yml
    input_mapping:
      git-kubo-deployment: git-kubo-deployment-output
    params:
      RELEASE_LIST: "cfcr-etcd"
  - put: git-kubo-deployment
    params:
      repository: git-kubo-deployment-output

- name: bump-docker-boshrelease
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-deployment
    - get: gcs-source-json
    - get: docker-boshrelease
      trigger: true
  - task: bump-kubo-docker
    file: git-kubo-ci/tasks/bump-boshrelease.yml
    input_mapping:
      boshrelease: docker-boshrelease
    params:
      RELEASE_NAME: docker
  - task: generate-compilation-manifest
    file: git-kubo-ci/tasks/generate-compilation-manifest.yml
    input_mapping:
      git-kubo-deployment: git-kubo-deployment-output
    params:
      RELEASE_LIST: "docker"
  - put: compilation-deployment
    params:
      manifest: compilation-manifest/manifest.yml
      source_file: gcs-source-json/source.json
    tags: ['gaffer']
  - task: export
    tags: ['gaffer']
    file: git-kubo-ci/tasks/export-release.yml
    input_mapping:
      git-kubo-deployment: git-kubo-deployment-output
    params:
      RELEASE_LIST: "docker"
  - put: gcs-precompiled-docker-untested
    params:
      file: compiled-releases/docker-*.tgz
  - task: bump-precompiled-releases-in-manifest
    file: git-kubo-ci/tasks/bump-precompiled-releases-in-manifest.yml
    input_mapping:
      git-kubo-deployment: git-kubo-deployment-output
    params:
      RELEASE_LIST: "docker"
  - put: git-kubo-deployment
    params:
      repository: git-kubo-deployment-output

- name: bump-windows-tools-release
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-deployment
    - get: gcs-source-json
    - get: windows-tools-release
      trigger: true
  - task: bump-windows-tools-release
    file: git-kubo-ci/tasks/bump-boshrelease.yml
    input_mapping:
       boshrelease: windows-tools-release
    params:
      RELEASE_NAME: windows-tools
      MODE: name
      OPSFILE: windows/add-worker.yml
  - put: git-kubo-deployment
    params:
      repository: git-kubo-deployment-output

- name: bump-windows-utilities-release
  plan:
  - aggregate:
    - get: git-kubo-ci
    - get: git-kubo-deployment
    - get: gcs-source-json
    - get: windows-utilities-release
      trigger: true
  - task: bump-windows-utilities-release
    file: git-kubo-ci/tasks/bump-boshrelease.yml
    input_mapping:
       boshrelease: windows-utilities-release
    params:
      RELEASE_NAME: windows-utilities
      MODE: name
      OPSFILE: windows/enable-rdp.yml
  - put: git-kubo-deployment
    params:
      repository: git-kubo-deployment-output
