#!/bin/bash

set -e -o pipefail

[ -z "${DEBUG}" ] || set -x

set -u

ci_dir="$(cd "$(dirname "$0")"; pwd)"

echo "======================================="
echo "| Setting kubo Concourse pipeline     |"
echo "======================================="
echo ""

print_usage() {
  echo "Usage:"
  echo "    $0 <pipeline name> [branch name] "
  echo ""
  echo "    valid pipeline names:"
  for name in ${ci_dir}/*.yml; do
    local pipeline_name
    pipeline_name="$(basename "${name}")"
    echo "        - ${pipeline_name%.yml}"
  done
  echo
  echo 'Use following command to set all pipelines'
  echo 'find * -maxdepth 0 -name \*.yml -exec ./set_pipeline  {} \;'
}

extract_pipeline_name() {
  local pipeline_name="$1"

  local pipeline_filename="${ci_dir}/${pipeline_name}.yml"
  if [ ! -f "${pipeline_filename}" ]; then
    pipeline_filename="${ci_dir}/${pipeline_name}"
    if [ ! -f "${pipeline_filename}" ]; then
      echo "Unknown pipeline name ${pipeline_name}"
      print_usage
      exit 1
    fi
  fi

  pipeline_name=$(basename "${pipeline_filename}")
  echo -n "${pipeline_name%.*}"
}

main() {
  local pipeline_name
  if [ "$#" == "0" ]; then
    print_usage
    exit 1
  fi
  pipeline_name=$(extract_pipeline_name "${1}")

  local pipeline_filename="${ci_dir}/${pipeline_name}.yml"
  local branch_name="master"

  if [ -z  "$(which lpass)" ]; then
    echo "Unable to locate the LastPass CLI"
    print_usage
    exit 1
  fi

  echo "${pipeline_name}"
  local current_branch_regex='-current-branch$'
  if [[ "${pipeline_name}" =~ $current_branch_regex ]]; then
    branch_name="${2:-$branch_name}"
    git_username=$(git config user.email | awk -F'=' '{print $2}' | awk -F'@' '{print $1}' | xargs)
    if [ ! -z "$git_username" ]; then
      pipeline_name="${pipeline_name}-${git_username}"
    else
      pipeline_name="${pipeline_name}-${RANDOM}"
    fi
  fi

  local ssh_key service_account slack_url github_token
  ssh_key="$(lpass show "Shared-Kubo/CI/git-ssh-key" --notes)"
  service_account="$(lpass show "Shared-Kubo/CI/bosh-deployer service key" --notes)"
  slack_url="$(lpass show "Shared-Kubo/CI/Slack Incoming Webhook" --url)"
  github_token="$(lpass show "Shared-Kubo/CI/pr-github-token" --notes)"


  trap 'rm "${ci_dir}/secrets.yml"' EXIT
  echo "---" > "${ci_dir}/secrets.yml"
  lpass show "Shared-Kubo/CI/kubo-ci" --notes >> "${ci_dir}/secrets.yml"
  lpass show "Shared-Kubo/CI/CF" --notes >> "${ci_dir}/secrets.yml"

  fly --target kubo sync > /dev/null
  erb "${pipeline_filename}" > /dev/null

  fly --target kubo set-pipeline --pipeline "${pipeline_name}" \
    --config <(erb "${pipeline_filename}") \
    --load-vars-from "${ci_dir}/secrets.yml" \
    --var git-ssh-key="${ssh_key}" \
    --var gcp-service-account="${service_account}" \
    --var slack-url="${slack_url}" \
    --var github-token-key="${github_token}" \
    --var branch-name="${branch_name}"
}

pushd "${ci_dir}" > /dev/null
  main "$@"
popd > /dev/null
