resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
- name: slack-alert
  type: slack-notification
  source:
    url: ((build-alert-slack-url))

- name: git-kubo-ci
  type: git
  source:
    uri: git@github.com:cloudfoundry-incubator/kubo-ci
    branch: master
    private_key: ((git-ssh-key.private_key))

- name: gcs-shipables
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    versioned_file: shipables/shipable_version
#azure_vanilla_turbulence
<% arr = %w(
aws_vanilla_integration
aws_old-release_upgrade
aws_vanilla_conformance
aws_vanilla_turbulence
aws_vanilla_security
azure_vanilla_conformance
azure_vanilla_integration
gcp_old-release_upgrade
gcp_custom-cidrs_integration
gcp_pod-security-policy_integration
gcp_two-cas_no-test
gcp_vanilla_conformance
gcp_vanilla_integration
gcp_vanilla_istio
gcp_vanilla_turbulence
) %>
<% arr.each do |pipeline| %>
- name: gcs-<%= pipeline %>-shipables
  type: gcs
  source:
    json_key: ((gcs-json-key))
    bucket: kubo-pipeline-store
    versioned_file: shipables/<%= pipeline %>-shipable
<% end %>

jobs:
- name: signal-aggregator
  plan:
  - aggregate:
    - get: git-kubo-ci
    <% arr.each do |pipeline|%>
    - get: gcs-<%= pipeline %>-shipables
      trigger: true
      version: every
    <% end %>
  - task: aggregate-test-signals
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: pcfkubo/kubo-ci
          tag: stable
      params:
        SLACK_MESSAGE_FILE: "slack/message"
        SHIPABLE_VERSION_FILE: "shipable_version/version"
      outputs:
      - name: slack
      - name: shipable_version
      inputs:
      - name: git-kubo-ci
      <% arr.each do |pipeline| %>
      - name: gcs-<%= pipeline %>-shipables
      <% end %>
      run:
        path: git-kubo-ci/scripts/aggregate-test-signals.rb
    on_success:
      put: gcs-shipables
      params:
        file: shipable_version/version
    ensure:
      put: slack-alert
      params:
        attachments_file: slack-notification/attachments
        text_file: "slack/message"


