#!/bin/bash
./v2_set_pipeline aws old-release upgrade
./v2_set_pipeline aws vanilla conformance
./v2_set_pipeline aws vanilla integration
./v2_set_pipeline aws vanilla turbulence
./v2_set_pipeline aws vanilla security

./v2_set_pipeline azure vanilla conformance
./v2_set_pipeline azure vanilla integration
./v2_set_pipeline azure vanilla turbulence
./v2_set_pipeline azure old-release upgrade

./v2_set_pipeline gcp vanilla conformance
./v2_set_pipeline gcp vanilla integration
./v2_set_pipeline gcp vanilla istio
./v2_set_pipeline gcp vanilla turbulence
./v2_set_pipeline gcp custom-cidrs integration
./v2_set_pipeline gcp old-release upgrade
./v2_set_pipeline gcp pod-security-policy integration
./v2_set_pipeline gcp two-cas no-test

./v2_set_pipeline vsphere vanilla conformance
./v2_set_pipeline vsphere vanilla integration
./v2_set_pipeline vsphere vanilla turbulence
./v2_set_pipeline vsphere old-release upgrade
./v2_set_pipeline vsphere vanilla security

./v2_set_pipeline vsphere-proxy vanilla conformance
./v2_set_pipeline vsphere-proxy vanilla integration
./v2_set_pipeline vsphere-proxy vanilla turbulence
./v2_set_pipeline vsphere-proxy vanilla security
