---
pins:
  - &CONCOURSE_VERSION {version: 3.5.0}
  - &GARDEN_RUNC_VERSION {version: 1.6.0}
  - &STEMCELL_VERSION {version: "3445.11"}
resource_types:
  - name: bosh-deployment
    type: docker-image
    source:
      repository: cloudfoundry/bosh-deployment-resource
resources:
  - name: concourse-release
    type: bosh-io-release
    source:
      repository: concourse/concourse

  - name: garden-runc-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/garden-runc-release

  - name: aws-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent

  - name: concourse-aws-deployment
    tags: [aws]
    type: bosh-deployment
    source:
      target: ((aws_director_internal_ip))
      client: admin
      client_secret: ((aws_admin_password))
      ca_cert: ((aws_director_ssl_ca))
      deployment: concourse-worker-aws

  - name: vsphere-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-vsphere-esxi-ubuntu-trusty-go_agent

  - name: concourse-vsphere-deployment
    tags: [vsphere]
    type: bosh-deployment
    source:
      target: ((vsphere_director_internal_ip))
      client: admin
      client_secret: ((vsphere_admin_password))
      ca_cert: ((vsphere_director_ssl_ca))
      deployment: concourse-worker

  - name: gcp-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-google-kvm-ubuntu-trusty-go_agent

  - name: concourse-gcp-deployment
    tags: [gcp]
    type: bosh-deployment
    source:
      target: ((gcp_director_internal_ip))
      client: admin
      client_secret: ((gcp_admin_password))
      ca_cert: ((gcp_director_ssl_ca))
      deployment: kubo-ci

  - name: openstack-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-openstack-kvm-ubuntu-trusty-go_agent

  - name: concourse-openstack-deployment
    tags: [openstack]
    type: bosh-deployment
    source:
      target: ((openstack_director_internal_ip))
      client: admin
      client_secret: ((openstack_admin_password))
      ca_cert: ((openstack_director_ssl_ca))
      deployment: concourse-worker-openstack


jobs:
  - name: deploy-concourse-workers-vsphere
    plan:
      - aggregate:
        - get: concourse-release
          version: *CONCOURSE_VERSION
        - get: garden-runc-release
          version: *GARDEN_RUNC_VERSION

        - get: vsphere-stemcell
          version: *STEMCELL_VERSION
        - get: concourse-vsphere-deployment
          tags: [vsphere]

      - put: concourse-vsphere-deployment
        tags: [vsphere]
        params:
          manifest: concourse-vsphere-deployment/manifest.yml
          releases:
            - concourse-release/*.tgz
            - garden-runc-release/*.tgz
          stemcells:
            - vsphere-stemcell/*.tgz

  - name: deploy-concourse-workers-aws
    plan:
      - aggregate:
        - get: concourse-release
          version: *CONCOURSE_VERSION
        - get: garden-runc-release
          version: *GARDEN_RUNC_VERSION

        - get: aws-stemcell
          version: *STEMCELL_VERSION
        - get: concourse-aws-deployment
          tags: [aws]

      - put: concourse-aws-deployment
        tags: [aws]
        params:
          manifest: concourse-aws-deployment/manifest.yml
          releases:
            - concourse-release/*.tgz
            - garden-runc-release/*.tgz
          stemcells:
            - aws-stemcell/*.tgz

  - name: deploy-concourse-gcp
    plan:
    - aggregate:
      - get: concourse-release
        passed:
        - deploy-concourse-workers-vsphere
        - deploy-concourse-workers-aws
        - deploy-concourse-workers-openstack
        trigger: true
        version: *CONCOURSE_VERSION
      - get: garden-runc-release
        version: *GARDEN_RUNC_VERSION
      - get: gcp-stemcell
        version: *STEMCELL_VERSION
      - get: concourse-gcp-deployment
        tags: [gcp]
    - put: concourse-gcp-deployment
      params:
        manifest: concourse-gcp-deployment/manifest.yml
        releases:
        - concourse-release/*.tgz
        - garden-runc-release/*.tgz
        stemcells:
        - gcp-stemcell/*.tgz
      tags: [gcp]

  - name: deploy-concourse-workers-openstack
    plan:
    - aggregate:
      - get: concourse-release
        version: *CONCOURSE_VERSION
      - get: garden-runc-release
        version: *GARDEN_RUNC_VERSION
      - get: openstack-stemcell
        version: *STEMCELL_VERSION
      - get: concourse-openstack-deployment
        tags:
        - openstack
    - put: concourse-openstack-deployment
      params:
        manifest: concourse-openstack-deployment/manifest.yml
        releases:
        - concourse-release/*.tgz
        - garden-runc-release/*.tgz
        stemcells:
        - openstack-stemcell/*.tgz
      tags:
      - openstack
