#!/bin/bash

# source this file to provide bash Utilities for updating pks-related pipelines

TARGET="kubo-pks"
TEAM_NAME="pks"

function login {
  fly --target $TARGET login \
    --concourse-url=https://ci.kubo.sh \
    --team-name=$TEAM_NAME \
    --open-browser
}

function update-team-permissions {
  fly --target $TARGET set-team \
    --team-name=$TEAM_NAME \
    --config concourse/team-configs/pks.yaml
}

function get-credhub-credentials {
  pushd ~/workspace/kubo-locks/concourse/gcp || return
    eval "$(bbl print-env)"
  popd || return
}

function copy-sshkey {
  get-credhub-credentials
  # TODO: find the real source of this val in lastpass or something
  EXISTING_VAL=$(credhub get -n /concourse/main/git-ssh-key -j)
  credhub set \
    --name /concourse/"$TEAM_NAME"/git-ssh-key \
    --private "$(echo "$EXISTING_VAL" | jq .value.private_key)" \
    --type ssh
}

function fly-verification-pipeline {
  fly --target $TARGET set-pipeline \
    --pipeline=minimum-release-verification \
    --config=pks-pipelines/minimum-release-verification/pipeline.yml
}

function fly-osl-pipeline {
  fly --target $TARGET set-pipeline \
    --pipeline=osl \
    --config=pks-pipelines/osl/pipeline.yml
}

#function main {
#  login
#  update-team-permissions
#  copy-sshkey
#  fly-verification-pipeline
#}

#main
