#!/bin/bash

set -e -o pipefail

ci_dir="$(cd "$(dirname "$0")"; pwd)/templates"

print_usage() {
  echo "Usage:"
  echo "    $0 <iaas> <pipeline name> [testcase] "
  echo ""
  echo "    valid iaas names:"
  for name in "${ci_dir}"/iaas/*.yml; do
    local iaas_name
    iaas_name="$(basename "${name}")"
    echo "        - ${iaas_name%.yml}"
  done
  echo ""
  echo "    valid pipeline names:"
  for name in "${ci_dir}"/ops-files/*.yml; do
    local pipeline_name
    pipeline_name="$(basename "${name}")"
    echo "        - ${pipeline_name%.yml}"
  done
  echo ""
  echo "    valid testcases names:"
  for name in "${ci_dir}"/iaas-testcase-ops-files/*.yml; do
    local testcase_name
    testcase_name="$(basename "${name}")"
    echo "        - ${testcase_name%.yml}"
  done
  echo
  echo 'Use following command to set all gcp pipelines'
  echo 'find ops-files/* -maxdepth 0 -name \*.yml -exec ./set_pipeline gcp $(basename {}) \;'
}

extract_pipeline_name() {
  local pipeline_name="$1"

  local pipeline_filename="${ci_dir}/ops-files/${pipeline_name}.yml"
  if [ ! -f "${pipeline_filename}" ]; then
    pipeline_filename="${ci_dir}/ops-files/${pipeline_name}"
    if [ ! -f "${pipeline_filename}" ]; then
      echo "Unknown pipeline name ${pipeline_name}"
      print_usage
      exit 1
    fi
  fi

  pipeline_name=$(basename "${pipeline_filename}")
  echo -n "${pipeline_name%.*}"
}

main() {
  local pipeline_name pipeline_config iaas_name testcase
  if [ "$#" -gt "3" ] || [ "$#" == "0" ]  || [ "$#" == "1" ]; then
    print_usage
    exit 1
  fi
  iaas_name=${1}
  pipeline_name=$(extract_pipeline_name "${2}")
  testcase="${3}"

  pipeline_config=$(cat "$ci_dir"/template.yml)
  local pipeline_ops_file="${ci_dir}/ops-files/${pipeline_name}.yml"
  local iaas_ops_file="${ci_dir}/iaas/${iaas_name}.yml"
  local iaas_testcase_ops_file="${ci_dir}/iaas-testcase-ops-files/${iaas_name}-${testcase}.yml"
  local iaas_vars_file="${ci_dir}/iaas/vars-files/${iaas_name}.yml"
  if [ -f "${pipeline_ops_file}" ]; then
    pipeline_config=$(bosh int <(echo "${pipeline_config}") --ops-file "${pipeline_ops_file}")
  fi
  if [ -f "${iaas_ops_file}" ]; then
    pipeline_config=$(bosh int <(echo "${pipeline_config}") --ops-file "${iaas_ops_file}")
  fi
  if [ -f "${iaas_testcase_ops_file}" ]; then
    pipeline_config=$(bosh int <(echo "${pipeline_config}") --ops-file "${iaas_testcase_ops_file}")
  fi

  fly --target kubo sync > /dev/null

  fly --target kubo set-pipeline \
    --config <(echo "${pipeline_config}") \
    --pipeline "${iaas_name}-${pipeline_name}" \
    -v iaas="${iaas_name}"
}

pushd "${ci_dir}" > /dev/null
  main "$@"
popd > /dev/null
