#!/bin/bash

set -e -o pipefail

ci_dir="$(cd "$(dirname "$0")"; pwd)/templates"

print_usage() {
  echo "Usage:" >&2
  echo "    $0 <iaas> <deployment_configuration> [testcase] " >&2
  echo "" >&2
  echo "    valid iaas names:" >&2
  for name in "${ci_dir}"/iaas/*.yml; do
    local iaas_name
    iaas_name="$(basename "${name}")"
    echo "        - ${iaas_name%.yml}" >&2
  done
  echo "" >&2
  echo "    valid deployment_configuration names:" >&2
  for name in "${ci_dir}"/deployment_configurations/*.yml; do
    local deployment_configuration
    deployment_configuration="$(basename "${name}")"
    echo "        - ${deployment_configuration%.yml}" >&2
  done
  echo "" >&2
  echo "    valid testcases names:" >&2
  for name in "${ci_dir}"/testcases/*.yml; do
    local testcase_name
    testcase_name="$(basename "${name}")"
    echo "        - ${testcase_name%.yml}" >&2
  done
}

extract_deployment_configuration() {
  local deployment_configuration="$1"

  local pipeline_filename="${ci_dir}/deployment-configurations/${deployment_configuration}.yml"
  if [ ! -f "${pipeline_filename}" ]; then
    pipeline_filename="${ci_dir}/deployment-configurations/${deployment_configuration}"
    if [ ! -f "${pipeline_filename}" ]; then
      echo "Unknown deployment configuration name: ${deployment_configuration}" >&2
      print_usage
      exit 1
    fi
  fi

  deployment_configuration=$(basename "${pipeline_filename}")
  echo -n "${deployment_configuration%.*}"
}

extract_testcase() {
  local testcase="$1"

  local pipeline_filename="${ci_dir}/testcases/${testcase}.yml"
  if [ ! -f "${pipeline_filename}" ]; then
    pipeline_filename="${ci_dir}/testcases/${testcase}"
    if [ ! -f "${pipeline_filename}" ]; then
      echo "Unknown testcase name: ${testcase}" >&2
      print_usage
      exit 1
    fi
  fi

  testcase=$(basename "${pipeline_filename}")
  echo -n "${testcase%.*}"
}

main() {
  local deployment_configuration pipeline_config iaas_name testcase
  if [ "$#" -gt "3" ] || [ "$#" == "0" ]  || [ "$#" == "1" ]; then
    print_usage
    exit 1
  fi
  iaas_name=${1}
  deployment_configuration=$(extract_deployment_configuration "${2}")
  testcase=$(extract_testcase "${3}")

  pipeline_config=$(cat "$ci_dir"/template.yml)
  local deployment_configuration_ops_file="${ci_dir}/deployment-configurations/${deployment_configuration}.yml"
  local iaas_ops_file="${ci_dir}/iaas/${iaas_name}.yml"
  local testcase_ops_file="${ci_dir}/testcases/${testcase}.yml"
  local iaas_testcase_ops_file="${ci_dir}/iaas-testcase-ops-files/${iaas_name}-${testcase}.yml"
  if [ -f "${deployment_configuration_ops_file}" ]; then
    pipeline_config=$(bosh int <(echo "${pipeline_config}") --ops-file "${deployment_configuration_ops_file}")
  fi
  if [ -f "${iaas_ops_file}" ]; then
    pipeline_config=$(bosh int <(echo "${pipeline_config}") --ops-file "${iaas_ops_file}")
  fi
  if [ -f "${testcase_ops_file}" ]; then
    pipeline_config=$(bosh int <(echo "${pipeline_config}") --ops-file "${testcase_ops_file}")
  fi
  if [ -f "${iaas_testcase_ops_file}" ]; then
    pipeline_config=$(bosh int <(echo "${pipeline_config}") --ops-file "${iaas_testcase_ops_file}")
  fi

  fly --target kubo sync > /dev/null

  fly --target kubo set-pipeline \
    --config <(echo "${pipeline_config}") \
    --pipeline "${iaas_name}-${deployment_configuration}-${testcase}" \
    -v iaas="${iaas_name}"
}

pushd "${ci_dir}" > /dev/null
  main "$@"
popd > /dev/null
