platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/build-kubo-release.sh

params:
  release: kubo-windows

inputs:
  - name: git-kubo-ci
  - name: git-kubo-windows-release
  - name: kubo-version
outputs:
  - name: kubo-windows-release
