platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/build-kubernetes-release.sh

params:
  RELEASE:

inputs:
  - name: git-kubo-ci
  - name: git-kubernetes-release
  - name: kubernetes-version
outputs:
  - name: kubernetes-release
