platform: linux
image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-pks-golf/pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/bump-stemcell.sh

inputs:
  - name: git-kubo-ci
  - name: git-kubo-release
  - name: stemcell
outputs:
  - name: git-kubo-release-output
