---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-pks-golf/pcfkubo/kubo-ci

inputs:
- name: git-kubo-ci
- name: git-kubo-deployment
- name: kubo-version
  optional: true
- name: compiled-releases

outputs:
- name: git-kubo-deployment-output

run:
  path: git-kubo-ci/scripts/bump-precompiled-releases-in-manifest.sh

params:
  RELEASE_LIST:
