platform: linux
image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-pks-golf/pcfkubo/kubo-ci
    tag: stable

inputs:
- name: kubo-lock
- name: git-kubo-ci

params:
  ENV_FILE:
  GCP_SERVICE_ACCOUNT:
run:
  path: git-kubo-ci/scripts/cleanup-environment.sh
