platform: linux
image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-pks-golf/pcfkubo/vsphere-cleaner
    tag: stable

inputs:
- name: kubo-lock
- name: git-kubo-ci

params:
  ENV_FILE:
run:
  path: bash
  args:
  - -ec
  - vsphere-cleaner "$ENV_FILE"
