platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/create-flannel-pr.sh
params:
  CFCR_USER_TOKEN: ""
  GIT_SSH_KEY: ""

inputs:
  - name: git-kubo-release-output
  - name: flannel-release
  - name: git-kubo-ci

