platform: linux
image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-pks-golf/pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/destroy-bosh.sh

inputs:
  - name: git-kubo-ci
  - name: git-kubo-deployment
  - name: git-bosh-deployment
  - name: gcs-bosh-state
  - name: gcs-bosh-creds
  - name: kubo-lock
