---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-pks-golf/pcfkubo/kubo-ci

inputs:
- name: git-kubo-ci
- name: kubo-lock
- name: gcs-bosh-creds

outputs:
- name: source-json

run:
  path: git-kubo-ci/scripts/generate-source-json.sh
