platform: linux
image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-pks-golf/pcfkubo/kubo-ci
inputs:
- name: source-json
outputs:
- name: director_uuid
run:
  path: bash
  args:
  - -c
  - |
    set -euo pipefail
    export BOSH_ENVIRONMENT="$(jq -r .target source-json/source.json)"
    export BOSH_CLIENT="$(jq -r .client source-json/source.json)"
    export BOSH_CLIENT_SECRET="$(jq -r .client_secret source-json/source.json)"
    export BOSH_CA_CERT="$(jq -r .ca_cert source-json/source.json)"
    mkdir -p director_uuid
    echo "director_uuid: \"$(bosh environment --json | jq -r .Tables[0].Rows[0].uuid)\"" > director_uuid/var.yml
