platform: linux
image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-pks-golf/pcfkubo/kubo-ci
    tag: stable
run:
  path: /bin/bash
  args:
  - -exc
  - |
    echo "No test was run!"
