platform: linux
image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-pks-golf/pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-deployment/bin/run_tests

inputs:
  - name: git-kubo-deployment
