platform: linux
image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-pks-golf/pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/run-k8s-security-tests.sh

params:
  DEPLOYMENT_NAME: ci-service

inputs:
  - name: git-kubo-ci
  - name: kubo-lock
    optional: true
