platform: linux
image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-pks-golf/pcfkubo/kubo-ci
    tag: stable

run:
  path: /bin/bash
  args:
  - -exc
  - |
    tar -xzf  gcs-kubo-release-pre/kubo-release*.tgz -C git-kubo-release/
    shopt -s dotglob # unpack hidden files, so we can mark version as shipable
    mv git-kubo-release/kubo-release*/* git-kubo-release/
inputs:
- name: gcs-kubo-release-pre

outputs:
- name: git-kubo-release
