platform: linux
image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-pks-golf/pcfkubo/kubo-ci
    tag: stable
inputs:
- name: git-kubo-ci
- name: kubo-lock
- name: gcs-bosh-creds
outputs:
- name: kubeconfig
params:
  DEPLOYMENT_NAME: "ci-service"
  CREDFILE: gcs-bosh-creds/creds.yml
  VARFILE: kubo-lock/metadata
  KUBECONFIG: kubeconfig/config
  API_URL: ""
run:
  path: git-kubo-ci/scripts/set_kubeconfig
