platform: linux
image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-pks-golf/pcfkubo/kubo-ci
    tag: stable
inputs:
- name: git-kubo-ci
- name: kubo-lock
outputs:
- name: kubeconfig
params:
  VARFILE: kubo-lock/metadata
  KUBECONFIG: kubeconfig/config
run:
  path: git-kubo-ci/scripts/set_kubeconfig_long_lived_director
