// Code generated by counterfeiter. DO NOT EDIT.
package vspherefakes

import (
	"context"
	"github.com/vmware/govmomi/object"
	"errors"
)

type FakeVmFinder struct {
	err error
}

func FailingFinder() FakeVmFinder {
	return FakeVmFinder{err: errors.New("Confucius says: sex and om.")}
}

func (fake FakeVmFinder) FindByIp(arg1 context.Context, arg2 *object.Datacenter, arg3 string, arg4 bool) (object.Reference, error) {
	return nil, fake.err
}
