#!/bin/bash

set -e

cleanerDir=$(dirname "${BASH_SOURCE[0]}")
GOPATH=$(cd "$cleanerDir/../../" && pwd)
export GOPATH

outputDir="$(cd "${1:-.}" && pwd)"
cd "$cleanerDir"
go build -o "$outputDir/vsphere-cleaner"

