#!/usr/bin/env bash

set -e -o pipefail

[[ -z "${DEBUG:-}" ]] || set -x

print_usage() {
cat << EOF
  Usage: $0 <BOSH environment path>
EOF
}

repo_directory() {
  echo -n "${PWD}/git-kubo-ci"
}

main() {
  if [ $# -ne 1 ] ; then
    print_usage
    exit 1
  fi

  local bosh_env=$(cd "$1"; pwd)
  local bosh_iaas="$(bosh int ${bosh_env}/director.yml --path '/iaas')"
  local cloud_config
  local ops_string=""
  local cloud_args=""

  if [[ ! -z "${CLOUD_CONFIG_OPS_FILES}" ]]; then
    while IFS=':' read -ra cloud_config_ops_files; do
      for ops_file in "${cloud_config_ops_files[@]}"; do
        ops_string="${ops_string} --ops-file=${ops_file}"
      done
    done <<< "${CLOUD_CONFIG_OPS_FILES}"
  fi

  cloud_args=$(echo -n "$(repo_directory)/configurations/${bosh_iaas}/cloud-config.yml" --vars-file ${bosh_env}/director.yml)

  bosh int ${cloud_args} ${ops_string}
}

[[ "$0" == "${BASH_SOURCE[0]}" ]] && main "$@"
