#!/bin/bash

if [ "$1" == "" ]; then
    echo "Usage: "
    echo "source set-bosh-env source.json"
    exit 1
fi

BOSH_CLIENT="$(bosh int "$1" --path=/client)"
BOSH_CLIENT_SECRET="$(bosh int "$1" --path=/client_secret)"
BOSH_CA_CERT="$(bosh int "$1" --path=/ca_cert)"
BOSH_ENVIRONMENT="$(bosh int "$1" --path=/target)"

export BOSH_CA_CERT BOSH_CLIENT BOSH_CLIENT_SECRET BOSH_ENVIRONMENT

