# apiVersion: certificates.k8s.io/v1
# kind: CertificateSigningRequest
# metadata:
#   name: test-csr
# spec:
#   groups:
#   - system:masters
#   - system:authenticated
#   request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2p6Q0NBWGNDQVFBd0tERVhNQlVHQTFVRUNoTU9jM2x6ZEdWdE9tMWhjM1JsY25NeERUQUxCZ05WQkFNVApCSFoxY25Zd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNycTAxcmx3RlBsVm9ZCml1bjJMdGsrbUExNmk0aW5GcEphaURUSk9VdGJoZTdtbUY2b2c2bFZXV0o5c0paVERvSmFOOGFJVVA4aUJkeXAKdmUzTFF1bk93UlphSkJqSVdLMU1ZeWlpeXZicWR3RHdwSWlYVmhsa3BLUGtKNzlNZXZEVXdsT2VsYkw5dXU4dQphTmV2cFBWUlY5b3QyZEJRZUFIRHVMcVpQUDJldWxwQ0pOUXcvZGVGNG1UejBBNUdUUFBaNHE1ZFZ2b2JnNWVsCk5INXdkc005WmxMdXU1bWF2UFdlU1MvWjAzNEs0Mk1zb2pXa296c25mejlpSFowZmtZWFFGUk5HbWxPZ2QrVnIKZ3U4UkRmUkVaTmFNTERoYTY1OFFBRDBRR3E5TGJUSzczOFdFUW5PUUgwc2lpVnpUQ0ZOL21JUk5Na2duU1pDUApiOVhLYVJIRkFnTUJBQUdnSWpBZ0Jna3Foa2lHOXcwQkNRNHhFekFSTUE4R0ExVWRFUVFJTUFhSEJBcjBBQ0l3CkRRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFFZVNJV3Bvb05CUkVOQ2R2Q0V0NVY3NURQTWFYMWZXSjBESFNKanoKeEhEMHQ2a3Vsd1F5eWpDVjN0K0pkUlVkR1hkUWlIcjN4VHZWNW5ITWRkOGxOYllWV0JmZ1JpZmt3WnNObFhlbwpqdHFOem5tSkF2SzBTRjBnVTRaTzNRWjFKY1dlT09ZZlk0bkE2QVdpRGZjQk9WSFZXblV6WEdTMzlhWVVzUC8wCktyRlJnelRyUjcwNWlzQmhPRHZsRzlmaVJ4NnJCa1FEdzdXbE1WQm5xdHExMS9DbjA2SkZNYWptWFhhZjBKN20KdnI1L2RCWkNJNER5Skt1azZYTG9oSGkvZnY0RUJpRE5YTGlTVmd4SUN5NkNVekhkUXJDbHh6ZG1WZ2tNZjRaNgoyQkthK29ldldLVFV0Qzlib3gvQ2xua3ZVRUN4eXByamhObGRDcW9JemVTSHdZVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
#   usages:
#   - digital signature
#   - key encipherment
#   - client auth
#   signerName: kubernetes.io/kube-apiserver-client


apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: test-csr
spec:
  groups:
  - system:nodes
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQzBEQ0NBYmdDQVFBd2ZERUxNQWtHQTFVRUJoTUNWVk14Q3pBSkJnTlZCQWdNQWtOQk1SVXdFd1lEVlFRSwpEQXh6ZVhOMFpXMDZibTlrWlhNeElEQWVCZ05WQkFzTUYwdDFZbVZ5Ym1WMFpYTWdWR2hsSUVoaGNtUWdWMkY1Ck1TY3dKUVlEVlFRRERCNXplWE4wWlcwNmJtOWtaVHByYVc1a0xXTnZiblJ5YjJ3dGNHeGhibVV3Z2dFaU1BMEcKQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURoNDZrZTRoRWZHeStKeVQ2TldDVzl3Rnkvdm41VgpROXllMlhvWEhPTzVZelMwcndMOG05RWo0UGI1Q2o0eHNiZkhQMENmaFplcTVjckltS2N4cTdMZ3NEY2I1UURpCmlGUy9udlhGR21OWXZKSHlyTE1Ec3UrUnVPb1JXcTk2Qk1zZmp4SE5aMEVTMlFnUTk4eE0yRVJVNlAyRExMNWEKdHpHOGc1MmgyV0RFVWthOGxzaW16R1BpLzJHMDV6MVFrVkZUS2d0cUtzb3dDNGlhSVpuNVFJVlNFV3pqWGczbwo4MWZXaVkxK1pNY1JkcWVKR09aSERZSmVoUnU1dE1rV1NhL25LTkxYbTJKcy9uQkZacVRNKys4WHhlNjcvcVVNCjJsdjFCSzZKSEJRYlY4eWFXTDd5N1g1enRGR1lkY0lIN2k1MzhkQXd5RlIxYVN6WkVLeC8wNGgvQWdNQkFBR2cKRHpBTkJna3Foa2lHOXcwQkNRNHhBREFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBT0hVSDRPbmZHRHhOUSsrUAovMXlyTXNlYTVSTmgxdXdmTUk5Vkh2bFl1cmo3QzBONTA3ekxyakowTjRRTGU3QWN4VnBNK2Y5dTFBeDg1YTlVClpaSzRHZWlBR1c3YVpINWEyVDBQbVU2ZmtXWktxRnQrdTcyUEIwdlRaUmVOdWhOTVBGZFZtbU9ma1hmdGxndDEKNWJtdGRMeWh3RUw0cURGSnJNQ1l5eDlSUmR3b1daYzhkMmJMQWMrWjZNWEpndTNOcVF4NHpOY2w5V3JPaEdsRQppVjd5anFqQUZ4OU5zOHU1ck9WVVlhTmJTckpGL2hUR0ZBZFgyZmluYUIwazJOZi9TUjVPZEZtTEkybXZqb1NtCnpObjFWb29qMmsyUU8xb3IrSU5KdDMyem9JOEtYMlBrR2E2YUljYy9RUHFEdDBKZmVyekhOMGE0NTZUWkFjK24KWDY0ZnlRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0t
  usages:
  - digital signature
  - key encipherment
  - client auth
  signerName: kubernetes.io/kube-apiserver-client-kubelet
# status:
#   conditions:
#   - message: "just do it"
#     reason: "because I said so"
#     type: Approved
#     status: "True"