apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: test-csr
spec:
  groups:
  - system:masters
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2p6Q0NBWGNDQVFBd0tERVhNQlVHQTFVRUNoTU9jM2x6ZEdWdE9tMWhjM1JsY25NeERUQUxCZ05WQkFNVApCSFoxY25Zd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUUNycTAxcmx3RlBsVm9ZCml1bjJMdGsrbUExNmk0aW5GcEphaURUSk9VdGJoZTdtbUY2b2c2bFZXV0o5c0paVERvSmFOOGFJVVA4aUJkeXAKdmUzTFF1bk93UlphSkJqSVdLMU1ZeWlpeXZicWR3RHdwSWlYVmhsa3BLUGtKNzlNZXZEVXdsT2VsYkw5dXU4dQphTmV2cFBWUlY5b3QyZEJRZUFIRHVMcVpQUDJldWxwQ0pOUXcvZGVGNG1UejBBNUdUUFBaNHE1ZFZ2b2JnNWVsCk5INXdkc005WmxMdXU1bWF2UFdlU1MvWjAzNEs0Mk1zb2pXa296c25mejlpSFowZmtZWFFGUk5HbWxPZ2QrVnIKZ3U4UkRmUkVaTmFNTERoYTY1OFFBRDBRR3E5TGJUSzczOFdFUW5PUUgwc2lpVnpUQ0ZOL21JUk5Na2duU1pDUApiOVhLYVJIRkFnTUJBQUdnSWpBZ0Jna3Foa2lHOXcwQkNRNHhFekFSTUE4R0ExVWRFUVFJTUFhSEJBcjBBQ0l3CkRRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFFZVNJV3Bvb05CUkVOQ2R2Q0V0NVY3NURQTWFYMWZXSjBESFNKanoKeEhEMHQ2a3Vsd1F5eWpDVjN0K0pkUlVkR1hkUWlIcjN4VHZWNW5ITWRkOGxOYllWV0JmZ1JpZmt3WnNObFhlbwpqdHFOem5tSkF2SzBTRjBnVTRaTzNRWjFKY1dlT09ZZlk0bkE2QVdpRGZjQk9WSFZXblV6WEdTMzlhWVVzUC8wCktyRlJnelRyUjcwNWlzQmhPRHZsRzlmaVJ4NnJCa1FEdzdXbE1WQm5xdHExMS9DbjA2SkZNYWptWFhhZjBKN20KdnI1L2RCWkNJNER5Skt1azZYTG9oSGkvZnY0RUJpRE5YTGlTVmd4SUN5NkNVekhkUXJDbHh6ZG1WZ2tNZjRaNgoyQkthK29ldldLVFV0Qzlib3gvQ2xua3ZVRUN4eXByamhObGRDcW9JemVTSHdZVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUgUkVRVUVTVC0tLS0tCg==
  usages:
  - digital signature
  - key encipherment
  - server auth
  - client auth
