name: ((deployment-name))

releases:
- name: kubo
  version: latest
- name: docker
  version: latest
- name: cfcr-etcd
  version: latest

stemcells:
- alias: default
  os: ubuntu-xenial
  version: "456.30"

update:
  canaries: 1
  max_in_flight: 1
  # both watch times are in milliseconds
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

instance_groups:
- name: print-version-test-ig
  azs:
  - z1
  instances: 1

  # IMPORTANT: for a VM with a single job, that job needs to be a default "service" rather than an errand,
  # since only a service implies that the VM needs to persist. So if we uncomment "lifecycle: errand", the VM gets destroyed by BOSH right after it is created.
  # lifecycle: errand
  jobs:
  - name: print-component-version
    release: kubo
  - name: print-docker-component-version
    release: docker
  - name: print-etcd-component-version
    release: cfcr-etcd
  vm_type: minimal
  stemcell: default
  # in megabytes
  persistent_disk: 20480 # (1024 * 20)
  networks:
  - name: default

addons: []
