#!/usr/bin/env bash

if which aws > /dev/null; then
  echo "Found 'aws'"
else
  echo "Command 'aws' not found" >&2
  exit 1
fi

if which bosh > /dev/null; then
  echo "Found bosh"
else
  echo "Command 'bosh' not found" >&2
  exit 1
fi

echo "Image is good"
