apiVersion: v1
kind: Service
metadata:
  labels:
    name: api-proxy
  name: api-proxy
spec:
  ports:
    - port: 8443
  selector:
    app: api-proxy
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-proxy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: api-proxy
    spec:
      containers:
      - name: api-proxy
        image: pcfkubo/api-proxy:stable
        ports:
        - containerPort: 8443
        volumeMounts:
        - mountPath: "/secrets"
          name: gaffer-api-secrets-volume
          readOnly: true
      volumes:
      - name: gaffer-api-secrets-volume
        secret:
          secretName: api-proxy
