---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-proxy-sa
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: api-proxy-psp
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
  # Required to prevent escalations to root.
  allowPrivilegeEscalation: false
  allowedCapabilities:
  - '*'
  # Allow core volume types.
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
  hostIPC: true
  hostPID: true
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
  runAsUser:
    # Require the container to run without root privileges.
    rule: 'RunAsAny'
  seLinux:
    # This policy assumes the nodes are using AppArmor rather than SELinux.
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
    # rule: 'MustRunAs'
    # ranges:
    #   # Forbid adding the root group.
    #   - min: 1
    #     max: 65535
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:api-proxy-psp
rules:
- apiGroups:
  - extensions
  resourceNames:
  - api-proxy-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:api-proxy-psp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:api-proxy-psp
subjects:
- kind: ServiceAccount
  name: api-proxy-sa
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: api-proxy
  name: api-proxy
spec:
  ports:
    - port: 8443
  selector:
    app: api-proxy
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-proxy
spec:
  selector:
    matchLabels:
        app: api-proxy
  replicas: 3
  template:
    metadata:
      labels:
        app: api-proxy
    spec:
      serviceAccountName: api-proxy-sa
      containers:
      - name: api-proxy
        image: gcr.io/cf-pks-golf/pcfkubo/api-proxy:stable
        ports:
        - containerPort: 8443
        volumeMounts:
        - mountPath: "/secrets"
          name: gaffer-api-secrets-volume
          readOnly: true
      volumes:
      - name: gaffer-api-secrets-volume
        secret:
          secretName: api-proxy
