---
apiVersion: v1
kind: Pod
metadata:
  name: hostpath-mount-cloudprovider
spec:
  containers:
  - name: busybox
    image: gcr.io/cf-pks-golf/busybox
    command:
      - sh
      - -c
      - 'while true; do sleep 1000; done'
    volumeMounts:
    - mountPath: /cloud-provider.ini
      name: cloudprovider
  volumes:
  - name: cloudprovider
    hostPath:
      path: /var/vcap/jobs/kubelet/config/cloud-provider.ini
      type: File
