---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hostpath-mount-cloudprovider
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: hostpath-mount-cloudprovider-psp
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default,docker/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  volumes:
    - 'hostPath'
  runAsUser:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:hostpath-mount-cloudprovider-psp
rules:
- apiGroups:
  - extensions
  resourceNames:
  - hostpath-mount-cloudprovider-psp
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:hostpath-mount-cloudprovider
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:hostpath-mount-cloudprovider-psp
subjects:
- kind: ServiceAccount
  name: hostpath-mount-cloudprovider
---
apiVersion: v1
kind: Pod
metadata:
  name: hostpath-mount-cloudprovider
spec:
  serviceAccountName: hostpath-mount-cloudprovider
  containers:
  - name: busybox
    image: gcr.io/cf-pks-golf/busybox
    command:
      - sh
      - -c
      - 'while true; do sleep 1000; done'
    volumeMounts:
    - mountPath: /cloud-provider.ini
      name: cloudprovider
  volumes:
  - name: cloudprovider
    hostPath:
      path: /var/vcap/jobs/kubelet/config/cloud-provider.ini
      type: File
