---
kind: Pod
apiVersion: v1
metadata:
  name: emptydir-pod
spec:
  volumes:
  - name: simple-vol
    emptyDir: {}
  - name: search-vol
    hostPath:
      path: /var/vcap/data/kubelet

  initContainers:
  - name: writing-container
    volumeMounts:
    - name: simple-vol
      mountPath: /var/simple

    image: gcr.io/cf-pks-golf/alpine
    command: ["/bin/sh"]
    args: ["-c", "touch /var/simple/find_me.txt"]

  containers:
  - name: shell-container
    volumeMounts:
    - name: simple-vol
      mountPath: /var/simple
    - name: search-vol
      mountPath: /var/search
    image: gcr.io/cf-pks-golf/alpine
    tty: true
    stdin: true
    command: ["/bin/sh"]

