#!/bin/bash
set -e

generate_manifest() {
  pushd "$(dirname "${BASH_SOURCE[0]}")" > /dev/null
    bosh-cli interpolate ../../../bosh-deployment/bosh.yml --ops-file  ../../../bosh-deployment/gcp/cpi.yml --vars-file director.yml --vars-file private.yml
  popd > /dev/null
}

generate_manifest
