#!/bin/bash
set -e

generate_manifest() {
  directory=$(dirname "${BASH_SOURCE[0]}")
  bosh-cli interpolate "$directory/concourse.yml" --vars-file "$directory/director.yml" --vars-file "$directory/private.yml"
}

generate_manifest
