---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-pks-golf/pcfkubo/kubo-ci
    tag: stable

inputs:
  - name: git-kubo-ci

params:
  BOSH_CA_CERT: ~
  BOSH_CLIENT: ~
  BOSH_CLIENT_SECRET: ~
  BOSH_DEPLOYMENT: ~
  BOSH_ENVIRONMENT: ~

run:
  path: git-kubo-ci/scripts/etcd/restart-cluster.sh
